# Generated by Django 6.0.4 on 2026-05-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
