# Generated by Django 6.0.4 on 2026-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='category',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
